esphome:
  name: boron
  friendly_name: boron
  # Restore saved brightness at boot
  on_boot:
    then:
      - light.turn_on:
          id: led_light
          brightness: !lambda 'return id(last_led_brightness);'

esp32:
  variant: esp32
  framework:
    type: esp-idf

logger:
ota:
  platform: esphome

safe_mode:
  disabled: true

api:
  reboot_timeout: 0s

wifi:
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi1_ssid
    password: !secret wifi1_password
  - ssid: !secret wifi2_ssid
    password: !secret wifi2_password
  - ssid: !secret wifi3_ssid
    password: !secret wifi3_password
  - ssid: !secret wifi4_ssid
    password: !secret wifi4_password

status_led:
  pin: GPIO14

web_server:
  port: 80

globals:
  - id: last_led_brightness
    type: float
    restore_value: true
    initial_value: '0.7' # default for first boot (0.0 - 1.0)

  - id: min_light_pc
    type: float
    initial_value: '0.1'



light:
  - platform: monochromatic
    name: LED
    id: led_light
    output: LED
    default_transition_length: 0s
    gamma_correct: 1.9

output:
  - platform: template
    id: LED
    type: float
    write_action:
      - output.set_level:
          id: LED1
          level: !lambda "return state;"
      - output.set_level:
          id: LED2
          level: !lambda "return state;"
      - output.set_level:
          id: LED3
          level: !lambda "return state;"
      - output.set_level:
          id: LED4
          level: !lambda "return state;"

  - platform: ledc
    pin: GPIO25
    id: LED1
    frequency: 19531

  - platform: ledc
    pin: GPIO26
    id: LED2
    frequency: 19531

  - platform: ledc
    pin: GPIO27
    id: LED3
    frequency: 19531

  - platform: ledc
    pin: GPIO4
    id: LED4
    frequency: 19531

sensor:
  - platform: adc
    pin: GPIO33
    id: temp_analog_reading
    attenuation: 12db

  - platform: resistance
    sensor: temp_analog_reading
    id: temp_resistance_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm

  - platform: ntc
    sensor: temp_resistance_reading
    name: Temperature
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K

  - platform: adc
    pin: GPIO34
    attenuation: 12db
    name: Voltage
    accuracy_decimals: 1
    filters:
      - multiply: 10.85

  - platform: adc
    pin: GPIO35
    attenuation: 12db
    name: Current
    accuracy_decimals: 2
    update_interval: 100ms
    filters:
      - multiply: 16.13
      - offset: -12.53
      - sliding_window_moving_average:
          window_size: 10
          send_every: 10
    unit_of_measurement: A

  - platform: adc
    pin: GPIO36
    name: Potentiometer
    id: potentiometer
    attenuation: 12db
    update_interval: 10ms
    accuracy_decimals: 2
    filters:
      - multiply: 2 # for 10k pullup
      - multiply: 1.23951219512 #  correction
      - multiply: 0.303030 # 1/3.3v to range 0-1
      - sliding_window_moving_average:
          window_size: 20
          send_every: 5
    on_value:
      - lambda: |-
          if (abs(id(last_led_brightness) - x) > 0.01) {
            id(last_led_brightness) = x;
            if (x <= id(min_light_pc)) id(led_light).make_call().set_brightness(id(min_light_pc)).perform();
            else if (x >= 1) id(led_light).make_call().set_brightness(1).perform();
            else id(led_light).make_call().set_brightness(x).perform();
          }
